[package]
name = "chesscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cake = { path = "../cake-rs/cake" }
cake_derive = { path = "../cake-rs/cake_derive" }
speculate = "0.1"
